### ISSUE TITLE
Full Example needed!

### ISSUE THREAD

**Issue by geogerar** [PTEz/PTEHorizontalTableView#1]
Hello,
Many thanks for your excellent tool.
I propose to include a full example, especially for header view and footer view, if you can please in order to help us!
I tried to implement these two methods but something I am not doing well.

Thanks again

George Gerardis

**Comment by mythodeia** [comment]
@geogerar 
i just added this

```
- (CGFloat)tableView:(PTEHorizontalTableView *)horizontalTableView widthForCellAtIndexPath:(NSIndexPath *)indexPath{
    return 90;
}

- (UIView*)tableView:(PTEHorizontalTableView*)horizontalTableView viewForHeaderInSection:(NSInteger)section{
    UIView *m = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 50,90)];
    [m setBackgroundColor:[UIColor darkGrayColor]];
    return m;
}

- (UIView*)tableView:(PTEHorizontalTableView*)horizontalTableView viewForFooterInSection:(NSInteger)section{
    UIView *m = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 50,90)];
    [m setBackgroundColor:[UIColor redColor]];
    return m;
}
```

and it showed both the header & footer
is that what you mean?

**Comment by geogerar** [comment]
Yes!!!!
This is exactly what I mean.....
Thank you very much!

On Tue, Jan 20, 2015 at 3:33 PM, Konstantinos K. notifications@github.com
wrote:

> @geogerar https://github.com/geogerar
> i just added this
> - (CGFloat)tableView:(PTEHorizontalTableView *)horizontalTableView widthForCellAtIndexPath:(NSIndexPath *)indexPath{
>   return 90;
>   }
> - (UIView_)tableView:(PTEHorizontalTableView_)horizontalTableView viewForHeaderInSection:(NSInteger)section{
>   UIView *m = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 50,82)];
>   [m setBackgroundColor:[UIColor darkGrayColor]];
>   return m;
>   }
> - (UIView_)tableView:(PTEHorizontalTableView_)horizontalTableView viewForFooterInSection:(NSInteger)section{
>   UIView *m = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 50,82)];
>   [m setBackgroundColor:[UIColor redColor]];
>   return m;
>   }
> 
> and it showed both the header & footer
> is that what you mean?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PTEz/PTEHorizontalTableView/issues/1#issuecomment-70653415
> .

## 

_Γιώργος Ν. Γεράρδης_

**Comment by rivera-ernesto** [comment]
Hi. Thank you for trying the library.

There is a Demo project, but maybe it does not demonstrate all feature. Could you try to add it there and make a pull request? Even if not finished I can work on top of it.

**Comment by rivera-ernesto** [comment]
Hi. Thank you for trying the library.

There is a Demo project, but maybe it does not demonstrate all feature. Could you try to add it there and make a pull request? Even if not finished I can work on top of it.

**Comment by geogerar** [comment]
Hello again,
Maybe there is an issue.....
The method "didSelectRowAtIndexPath" is not working.....
Can you please take a look and fix it?
Thanks again

George Gerardis

On Tue, Jan 20, 2015 at 3:33 PM, Konstantinos K. notifications@github.com
wrote:

> @geogerar https://github.com/geogerar
> i just added this
> - (CGFloat)tableView:(PTEHorizontalTableView *)horizontalTableView widthForCellAtIndexPath:(NSIndexPath *)indexPath{
>   return 90;
>   }
> - (UIView_)tableView:(PTEHorizontalTableView_)horizontalTableView viewForHeaderInSection:(NSInteger)section{
>   UIView *m = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 50,82)];
>   [m setBackgroundColor:[UIColor darkGrayColor]];
>   return m;
>   }
> - (UIView_)tableView:(PTEHorizontalTableView_)horizontalTableView viewForFooterInSection:(NSInteger)section{
>   UIView *m = [[UIView alloc] initWithFrame:CGRectMake(0, 0, 50,82)];
>   [m setBackgroundColor:[UIColor redColor]];
>   return m;
>   }
> 
> and it showed both the header & footer
> is that what you mean?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PTEz/PTEHorizontalTableView/issues/1#issuecomment-70653415
> .

## 

_Γιώργος Ν. Γεράρδης_

**Comment by geogerar** [comment]
Hello again,
Maybe there is an issue.....
The method "didSelectRowAtIndexPath" is not working.....
Can you please take a look and fix it?
Thanks again

George Gerardis

On Tue, Jan 20, 2015 at 7:29 PM, Ernesto Rivera notifications@github.com
wrote:

> Hi. Thank you for trying the library.
> 
> There is a Demo project, but maybe it does not demonstrate all feature.
> Could you try to add it there and make a pull request? Even if not finished
> I can work on top of it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/PTEz/PTEHorizontalTableView/issues/1#issuecomment-70695387
> .

## 

_Γιώργος Ν. Γεράρδης_

**Comment by mythodeia** [comment]
@rivera-ernesto this pull request https://github.com/PTEz/PTEHorizontalTableView/pull/3
fixes https://github.com/PTEz/PTEHorizontalTableView/issues/1 & https://github.com/PTEz/PTEHorizontalTableView/issues/2

thanks for the library Ernesto
