### ISSUE TITLE
Maybe an issue!

### ISSUE THREAD

**Issue by geogerar** [PTEz/PTEHorizontalTableView#2]
Hello again,
Maybe there is an issue.....
The method "didSelectRowAtIndexPath" is not working.....
Can you please take a look and fix it?
Thanks again

George Gerardis

**Comment by mythodeia** [comment]
@geogerar 
go to the storyboard and tap on the tableview, not the horizontal table view.
Find the property called selection. Change it to "single selection"
you are all set

Regards
Konstantinos K.

**Comment by rivera-ernesto** [comment]
Thanks @mythodeia !
